project:
  type: website
  output-dir: docs

website:
  title: "Welcome"
  favicon: images/favicon.jpg
  navbar:
    logo: images/logo.jpg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: genai.qmd
        text: GenAI Reflection
    right:
      - icon: github
        href: https://github.com/Catefishh/
        aria-label: Github

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


